#!/bin/bash

sudo apt install -y cups libcupsimage2

wget http://gdlp01.c-wss.com/gds/5/0100006265/01/cnijfilter2-5.00-1-deb.tar.gz
tar -xf cnijfilter2-5.00-1-deb.tar.gz
cnijfilter2-5.00-1-deb/install.sh --bit64
# follow instructions
rm -rv cnijfilter2-5.00-1-deb*

wget http://gdlp01.c-wss.com/gds/1/0100006271/01/scangearmp2-3.00-1-deb.tar.gz
tar -xf scangearmp2-3.00-1-deb.tar.gz
sudo apt install -y libpango1.0-0  # is needed for scangearmp2
scangearmp2-3.00-1-deb/install.sh --bit64
rm -rv scangearmp2-3.00-1-deb*
