#!/bin/bash

layout=$(setxkbmap -query | grep ^layout | awk '{print $2}')
if [ "$layout" = "de" ]; then
    setxkbmap us
    polybar-msg hook kb-layout-toggle 1
elif [ "$layout" = "us" ]; then
    setxkbmap de
    polybar-msg hook kb-layout-toggle 2
else
    notify-send polybar "Unknown keyboard layout '$layout'"
fi
