#!/bin/bash

battery_info=$(acpi -b | grep -v unavailable)
battery_percentage=$(echo "$battery_info" | cut -d ' ' -f 4 | grep -o '[0-9]*')
battery_state=$(echo "$battery_info" | cut -d ' ' -f 3 | sed 's/,//g')

notify-send "Battery: $battery_percentage %" "$battery_state"
